#!/usr/bin/env bash
# script that configures a new Ubuntu machine
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
