#!/usr/bin/env bash
# script that configures a new Ubuntu machine
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /etc/nginx/html/index.html
sudo service nginx restart
