#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
# that contains the string Ceci n'est pas une page
sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Hello World!" | sudo tee /etc/nginx/html/index.html
sudo touch /etc/nginx/html/custom_404.html
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/custom_404.html
echo "server {
        listen 80 default_server;
	listen [::]:80 default_server;
	root   /etc/nginx/html;
	index  index.html index.htm;

	location /redirect_me {
	        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

        error_page 404 /custom_404.html;
	location /not-found {
	        root /etc/nginx/html;
		internal;
	}
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
