#!/usr/bin/env bash
# Displays the content of the file /etc/passwd, using the while loop + IFS

while IFS=':' read -r USERNAME GROUP_ID HOME_DIRECTORY COMMAND USER_ID PASSWORD USER_ID_INFO
do
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
done < "/etc/passwd"
